sudo: false
language: java
before_install:
- openssl aes-256-cbc -K $encrypted_de05a52b3035_key -iv $encrypted_de05a52b3035_iv
  -in alecgibson-efee5c6896f7.json.enc -out alecgibson-efee5c6896f7.json -d
jdk: oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
deploy:
  provider: gae
  keyfile: alecgibson-efee5c6896f7.json
  project: alecgibson-167206
  default: true
  on: master
