language: java

jdk: oraclejdk8

# Avoid uploading the Gradle cache to Travis
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# See https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer